# Generated by Django 3.0.7 on 2020-11-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('skill_type', models.CharField(choices=[('PROGRAMMING LANGUAGE', 'Programming Language'), ('WEB FRAMEWORK', 'Web Framework'), ('VERSION CONTROL', 'Version Control'), ('ALGORIGHTM', 'DS and Algorithm'), ('BACKEND FRAMEWORK', 'Backend Framework'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=50)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=200)),
                ('achievements', models.ManyToManyField(to='profiles.Achievement')),
                ('skills', models.ManyToManyField(to='profiles.Skill')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
