# Generated by Django 3.0.7 on 2020-10-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('skill_type', models.CharField(choices=[('PROGRAMMING LANGUAGE', 'Programming Language'), ('WEB FRAMEWORK', 'Web Framework'), ('VERSION CONTROL', 'Version Control'), ('ALGORIGHTM', 'DS and Algorithm')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Skill'),
        ),
    ]
