# Generated by Django 3.0.7 on 2020-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201031_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(default='Coding', max_length=50),
        ),
    ]
