# Generated by Django 3.0.7 on 2020-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='profiles.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('PROGRAMMING LANGUAGE', 'Programming Language'), ('WEB FRAMEWORK', 'Web Framework'), ('VERSION CONTROL', 'Version Control'), ('ALGORIGHTM', 'DS and Algorithm')], max_length=50),
        ),
    ]
