# Generated by Django 3.0.7 on 2020-10-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201031_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('PROGRAMMING LANGUAGE', 'Programming Language'), ('WEB FRAMEWORK', 'Web Framework'), ('VERSION CONTROL', 'Version Control'), ('ALGORIGHTM', 'DS and Algorithm'), ('BACKEND FRAMEWORK', 'Backend Framework'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
