# Generated by Django 3.0.7 on 2020-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(default='projects/default.jpg', upload_to='projects/')),
                ('description', models.TextField()),
                ('verify_url', models.URLField()),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
