# Generated by Django 3.0.7 on 2020-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201108_1551'),
        ('projects', '0003_auto_20201108_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.ManyToManyField(blank=True, to='profiles.Skill'),
        ),
    ]
