# Generated by Django 3.0.7 on 2020-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_tech_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='verify_url',
            field=models.URLField(blank=True),
        ),
    ]
