# Generated by Django 3.0.7 on 2020-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(default='projects/default.jpg', upload_to='company/projects/')),
                ('description', models.TextField()),
                ('verify_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tech_type', models.CharField(choices=[('PROGRAMMING LANGUAGE', 'Programming Language'), ('WEB FRAMEWORK', 'Web Framework'), ('VERSION CONTROL', 'Version Control'), ('ALGORIGHTM', 'DS and Algorithm'), ('BACKEND FRAMEWORK', 'Backend Framework'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=50)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(default='company/default.jpg', upload_to='company/')),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('currently_working', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200)),
                ('projects', models.ManyToManyField(to='workexperiences.CompanyProject')),
                ('techs', models.ManyToManyField(to='workexperiences.Technology')),
            ],
        ),
    ]
