# Generated by Django 3.0.7 on 2020-11-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='verify_url',
            field=models.URLField(null=True),
        ),
    ]
