# Generated by Django 3.0.7 on 2020-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0002_auto_20201108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='image',
            field=models.ImageField(default='static/defaultProject.jpg', upload_to='company/projects/'),
        ),
    ]
