# Generated by Django 3.0.7 on 2020-11-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0002_auto_20201105_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='verify_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
