# Generated by Django 3.0.7 on 2020-11-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0003_auto_20201105_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='company/default.jpg', upload_to='company/'),
        ),
    ]
