# Generated by Django 3.0.7 on 2020-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0003_auto_20201108_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='image',
            field=models.ImageField(upload_to='company/projects/'),
        ),
    ]
