# Generated by Django 3.0.7 on 2020-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0004_auto_20201108_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='image',
            field=models.ImageField(null=True, upload_to='company/projects/'),
        ),
    ]
