# Generated by Django 3.0.7 on 2020-11-08 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0005_auto_20201108_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='company/projects/'),
            preserve_default=False,
        ),
    ]
