# Generated by Django 3.0.7 on 2020-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0006_auto_20201108_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='company/'),
        ),
    ]
