# Generated by Django 3.0.7 on 2020-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0007_auto_20201108_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='tech_used',
            field=models.ManyToManyField(blank=True, to='workexperiences.Technology'),
        ),
    ]
