# Generated by Django 3.0.7 on 2020-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperiences', '0009_auto_20201109_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
