# Generated by Django 3.0.7 on 2020-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('issued_by', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('is_lifetime_valid', models.BooleanField(default=False)),
                ('image', models.ImageField(default='certificates/default.jpg', upload_to='certificates/')),
                ('verify_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='profiles.Skill')),
            ],
        ),
    ]
