# Generated by Django 3.0.7 on 2020-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_auto_20201108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, upload_to='certificates/'),
        ),
    ]
