# Generated by Django 3.0.7 on 2020-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201108_1551'),
        ('certifications', '0003_auto_20201108_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.Skill'),
        ),
    ]
