# Generated by Django 3.0.7 on 2020-11-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_auto_20201109_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_lifetime_valid',
        ),
    ]
